# stage data by copying source data to target.  Staging directories created
# Usage: 
#  stage_data.sh [options] analysis datadir datatype
#
# analysis: canonical analysis name, e.g., WGS-Germline
# datadir: root directory of data
# datatype: type of data, i.e., suffix of data name
# source-es: experimental strategy of input data: WGS, WXS, or RNA-Seq 
#   this is used only to get the path to the appropriate BamMap file, which is parsed to get all cases
#
# There are assumptions about the filename of the source data; currently, it is assumed
# to be of the format CASE.datatype (works for Song's VCF and MAF files).  Other formats will
# be introduced ad hoc 
#
# Options:
# -z: compress the file while staging
# -f: force overwrite of target even if it exists
# -d: dry run.  Only pretend to copy
# -1: Stop after one case

source submit_config.sh


# Make destination directory
function make_staging_dir {
    CANCER=$1
    mkdir -p $(getd $CANCER $ANALYSIS)
}

function process_wrapper {
    # copy data generated by somatic or germline wrappers into staging directory, 
    # It is assumed data files are named CASE.xxx, where xxx is given by datatype argument
    # Add analysis name to front of filename.
    # If compressing, filename has .gz appended
    CASE=$1

    CANCER=$(cut -f 1,2 $SR | grep $CASE | cut -f 2 | sort -u)

    # this is the source filename - specific to Song's workflow
    FN="$DATD/${CASE}.${DATFT}"

    if [ ! -e $FN ]; then  # Might be good to have option here to either warn or quit 
        >&2 echo $FN does not exist.  Quitting
        exit 1
    fi

    # Staging directory
    DESTD=$(getd $CANCER $ANALYSIS)
    if [ $COMPRESS ]; then
        DESTFN="$DESTD/${ANALYSIS}.${CASE}.${DATFT}.gz"
    else
        DESTFN="$DESTD/${ANALYSIS}.${CASE}.${DATFT}"
    fi

    if [ -e $DESTFN ] && [ -s $DESTFN ];  then  # file exists and is not zero size
        if [  $FORCE_OVERWRITE ]; then
            >&2 echo Destination file $DESTFN exists.  Overwriting
        else
            >&2 echo Destination file $DESTFN exists.  Skipping
            return
        fi
    fi

    if [ $COMPRESS ]; then
        >&2 echo Compressing $FN to $DESTFN
        if [ $DRYRUN ]; then
            echo gzip -v - \<$FN \> $DESTFN
        else 
            gzip -v - <$FN > $DESTFN
        fi
    else
        >&2 echo Copying $FN to $DESTFN
        if [ $DRYRUN ]; then
            echo cp $FN $DESTFN
        else
            cp $FN $DESTFN
        fi
    fi
}

# http://wiki.bash-hackers.org/howto/getopts_tutorial
while getopts ":dzf1" opt; do
  case $opt in
    d) # Dry run 
      >&2 echo "Dry run" >&2
      DRYRUN=1
      ;;
    z) # compress while copying 
      >&2 echo "Compressing" >&2
      COMPRESS=1
      ;;
    f)  
      >&2 echo "Force Overwrite" >&2
      FORCE_OVERWRITE=1
      ;;
    1)  
      STOPATONE=1
      ;;
#    x) # example of value argument
#      FILTER=$OPTARG
#      >&2 echo "Setting memory $MEMGB Gb" 
#      ;;
    \?)
      >&2 echo "Invalid option: -$OPTARG" 
      exit 1
      ;;
    :)
      >&2 echo "Option -$OPTARG requires an argument." 
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

# Require 3 arguments
if [ "$#" -ne 4 ]; then
    >&2 echo Error: Require 4 arguments: analysis, datadir, datatype, source_es
    exit 1  # exit code 1 indicates error
fi

ANALYSIS=$1  # e.g. WGS-Somatic
DATD=$2
DATFT=$3
SOURCE_ES=$4

mkdir -p $STAGE_ROOT
echo Writing data to $STAGE_ROOT

# Make staging directories
for D in $DISEASES; do
    make_staging_dir $D
done

# get the BamMap path for this particular experimental strategy 
BM=$(getBM $SOURCE_ES)


while read CASE; do

    [[ $CASE = \#* ]] && continue  # Skip commented out entries
    >&2 echo Processing $CASE

    process_wrapper $CASE

    if [ $STOPATONE ]; then
        >&2 echo Stopping after one
        exit 0  # 0 indicates no error 
    fi

done < <(grep -v "^#" $BM | cut -f 2 | sort -u)  # pull out all case IDs out of BamMap and loop through them
